### ISSUE TITLE
The Norwegian translation is not Bokmål, but Nynorsk

### ISSUE THREAD

**Issue by joystein** [ichthyosaurus/harbour-todolist#23]
The translation i submitted in:

https://github.com/ichthyosaurus/harbour-todolist/pull/11

is actually nynorsk (nn-NO) and not bokmål (nb-NO).

It seem like this is the basis for whats in weblate. So if it could be changed there and other places where its needed, then I could maybe bring the translation up to date.

**Comment by ichthyosaurus** [comment]
Oh boy, that's an unfortunate mistake, thank you for the heads up!

I hope the Nynorsk translations haven't propagated into other apps and Opal modules that only have Bokmål translations - otherwise all my apps and modules now have a mix of Nynorsk and Bokmål, pretending to be Bokmål...

Fixing it for this app should be rather straightforward. I just have to investigate if other apps are affected as well.

**Comment by ichthyosaurus** [comment]
I fixed it for Todolist, which in turn means I can propagate the new Nynorsk translation to my other apps :). I think the Bokmål translations should actually be fine...

**Comment by joystein** [comment]
Thanks! Will have a look at the translations when i find time and see if there anything to update.
